name: jax
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jax
  - jaxlib
  - flax
  - optax
  - hydra-core
  - wandb
  - tensorboard
  - tensorboardX
  - numpy
  - pandas
  - scipy
  - matplotlib
  - tqdm
  - pip
  - pip:
    - orbax-checkpoint